/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.List;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rolandas
 */
public class Studentas extends javax.swing.JFrame {

    
    
    public Studentas() {
        initComponents();
         showData();
         
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StudentuSarasas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NrSalinti = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StNr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        StVard = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        StPavard = new javax.swing.JTextField();
        StDalVid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NaujasStudentas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        VardasUpdate = new javax.swing.JTextField();
        PavardeUpdate = new javax.swing.JTextField();
        DalykaiIrVidurkiaiUpdate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        UpdateStudentas = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        IstrintiDb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentuSarasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NR", "VARDAS", "PAVARDE", "DALYKAI_VIDURKIAI"
            }
        ));
        StudentuSarasas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentuSarasasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentuSarasas);
        if (StudentuSarasas.getColumnModel().getColumnCount() > 0) {
            StudentuSarasas.getColumnModel().getColumn(0).setResizable(false);
            StudentuSarasas.getColumnModel().getColumn(1).setPreferredWidth(200);
            StudentuSarasas.getColumnModel().getColumn(2).setPreferredWidth(200);
            StudentuSarasas.getColumnModel().getColumn(3).setPreferredWidth(600);
        }

        jLabel1.setText("Pasalinti studenta iveskite jo ID lenteleje (ID prasideda nuo 0) ");

        jButton1.setText("salinti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NrSalinti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NrSalintiActionPerformed(evt);
            }
        });

        jLabel2.setText("Naujo Studento Kurimas");

        jLabel4.setText("Iveskite studento numeri");

        jLabel5.setText("Iveskite studento varda");

        jLabel6.setText("Iveskite studento pavarde");

        StPavard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StPavardActionPerformed(evt);
            }
        });

        jLabel7.setText("Iveskite dalykus ir vidurkius");

        NaujasStudentas.setText("Issaugoti studenta");
        NaujasStudentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaujasStudentasActionPerformed(evt);
            }
        });

        jLabel8.setText("Esamo Studento update");

        jLabel10.setText(" Vardas");

        jLabel11.setText(" Pavarde");

        jLabel13.setText("dalykai ir vidurkiai");

        UpdateStudentas.setText("Update");
        UpdateStudentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStudentasActionPerformed(evt);
            }
        });

        jLabel9.setText("Istrinti visus db elementus");

        IstrintiDb.setText("Istrinti");
        IstrintiDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IstrintiDbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(StNr, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                            .addComponent(StVard)
                                            .addComponent(StPavard)
                                            .addComponent(StDalVid)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NaujasStudentas)
                                .addGap(93, 93, 93))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NrSalinti, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IstrintiDb)
                                .addGap(546, 546, 546))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(288, 288, 288)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(PavardeUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(VardasUpdate)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DalykaiIrVidurkiaiUpdate)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(UpdateStudentas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 73, Short.MAX_VALUE)))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4))
                            .addComponent(StNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(StVard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(StPavard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StDalVid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(NaujasStudentas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VardasUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PavardeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(IstrintiDb)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NrSalinti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DalykaiIrVidurkiaiUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addGap(18, 18, 18)
                .addComponent(UpdateStudentas)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public ArrayList<StudentasDuom>studentai(){
        Connection myconObj=null;
        Statement mystatObj=null;
        ResultSet myresObj=null;
        ArrayList<StudentasDuom> studentai= new ArrayList<>();
        String query="Select * from rolandas.studentai";
        try{
            myconObj= DriverManager.getConnection("jdbc:derby://localhost:1527/MyDataBase", "rolandas", "ulevrola123");
            mystatObj=myconObj.createStatement();
            myresObj=mystatObj.executeQuery(query);
            while(myresObj.next()){
                StudentasDuom tempStudentas=new StudentasDuom();
                tempStudentas.Nr=myresObj.getInt("NR");
                tempStudentas.vardas=myresObj.getString("Vardas");
                tempStudentas.pavarde=myresObj.getString("Pavarde");
                tempStudentas.dalykai_vidurkiai=myresObj.getString("FiveThings");
                studentai.add(tempStudentas);
            }
        }
        catch(SQLException e){
            e.printStackTrace();    
        }
        return studentai;
    }
     
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
         Connection myconObj=null;
         Statement mystatObj=null;
         ResultSet myresObj=null;
         int numeris=Integer.parseInt(NrSalinti.getText());
         DefaultTableModel model = (DefaultTableModel) StudentuSarasas.getModel();
         String query=("DELETE FROM rolandas.studentai WHERE Nr="+numeris);   
        try {
            myconObj= DriverManager.getConnection("jdbc:derby://localhost:1527/MyDataBase", "rolandas", "ulevrola123");
            PreparedStatement st = myconObj.prepareStatement("DELETE FROM rolandas.studentai WHERE Nr="+numeris);
            st.executeUpdate();
            model.removeRow(numeris);
            
        } catch (SQLException ex) {
            Logger.getLogger(Studentas.class.getName()).log(Level.SEVERE, null, ex);
        }
           
             //ArrayList<StudentasDuom>studentai2=studentai();
             //
             
            // model.removeRow(numeris);
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NrSalintiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NrSalintiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NrSalintiActionPerformed

    private void StPavardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StPavardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StPavardActionPerformed

    private void NaujasStudentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaujasStudentasActionPerformed
         Connection myconObj=null;
         Statement mystatObj=null;
         ResultSet myresObj=null;
         
         DefaultTableModel model = (DefaultTableModel) StudentuSarasas.getModel();
         int tempNr=Integer.parseInt(StNr.getText());
         String tempVardas=StVard.getText();
         String tempPavarde=StPavard.getText();
         String tempDalykaiVidurkiai=StDalVid.getText();
          String query = " insert into rolandas.studentai (nr, vardas, pavarde, fivethings)"
        + " values (?, ?, ?, ?)";
          
        try {
            myconObj= DriverManager.getConnection("jdbc:derby://localhost:1527/MyDataBase", "rolandas", "ulevrola123");
            PreparedStatement st = myconObj.prepareStatement(query);
            Object[]row=new Object[5];
            st.setInt(1, tempNr);
            st.setString(2, tempVardas);
            st.setString(3, tempPavarde);
            st.setString(4, tempDalykaiVidurkiai);
            st.executeUpdate();
            row[0]=tempNr;
            row[1]=tempVardas;
            row[2]=tempPavarde;
            row[3]=tempDalykaiVidurkiai;
            model.addRow(row);
            
        } catch (SQLException ex) {
            Logger.getLogger(Studentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NaujasStudentasActionPerformed

    private void StudentuSarasasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentuSarasasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel)StudentuSarasas.getModel();
        int selectedRowIndex= StudentuSarasas.getSelectedRow();
        
        VardasUpdate.setText(model.getValueAt(selectedRowIndex, 1).toString());
        PavardeUpdate.setText(model.getValueAt(selectedRowIndex, 2).toString());
        DalykaiIrVidurkiaiUpdate.setText(model.getValueAt(selectedRowIndex, 3).toString());
        
    }//GEN-LAST:event_StudentuSarasasMouseClicked

    private void UpdateStudentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStudentasActionPerformed
         Connection myconObj=null;
         Statement mystatObj=null;
         ResultSet myresObj=null;
         int selectedRowIndex= StudentuSarasas.getSelectedRow();
          ArrayList<StudentasDuom>studentai=studentai();
         DefaultTableModel model = (DefaultTableModel) StudentuSarasas.getModel();
         String tempNr=model.getValueAt(selectedRowIndex, 0).toString();
         String tempVardas=VardasUpdate.getText();
         String tempPavarde=PavardeUpdate.getText();
         String tempDalykaiVidurkiai=DalykaiIrVidurkiaiUpdate.getText();
           String query = "update rolandas.studentai  set vardas = ?, pavarde = ?, fivethings = ?  where Nr = ?";
          
        try {
            myconObj= DriverManager.getConnection("jdbc:derby://localhost:1527/MyDataBase", "rolandas", "ulevrola123");
            PreparedStatement st = myconObj.prepareStatement(query);
            Object[]row=new Object[5];
           
            
            st.setString(1, tempVardas);
            st.setString(2, tempPavarde);
            st.setString(3, tempDalykaiVidurkiai);
            st.setString(4, tempNr);
            st.executeUpdate();
            
        for(int i=studentai.size()-1;i>=0;i--){ 
            model.removeRow(i);
        }
        studentai=studentai();
        for(int i=0;i<studentai.size();i++){
            row[0]=studentai.get(i).Nr;
            row[1]=studentai.get(i).vardas;
            row[2]=studentai.get(i).pavarde;
            row[3]=studentai.get(i).dalykai_vidurkiai;
            //System.out.println(studentai.get(i).Nr+studentai.get(i).vardas+studentai.get(i).pavarde+studentai.get(i).dalykai_vidurkiai); 
            model.addRow(row);
        }
        
        
    }
            
         catch (SQLException ex) {
            Logger.getLogger(Studentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateStudentasActionPerformed

    private void IstrintiDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IstrintiDbActionPerformed
        Connection myconObj=null;
         Statement mystatObj=null;
         ResultSet myresObj=null;
          ArrayList<StudentasDuom>studentai=studentai();
         DefaultTableModel model = (DefaultTableModel) StudentuSarasas.getModel();
           String query = "DELETE from  rolandas.studentai";
        try {
            myconObj= DriverManager.getConnection("jdbc:derby://localhost:1527/MyDataBase", "rolandas", "ulevrola123");
            PreparedStatement st = myconObj.prepareStatement(query);
            st.executeUpdate();
            model.setRowCount(0);
    }
            
         catch (SQLException ex) {
            Logger.getLogger(Studentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IstrintiDbActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentas().setVisible(true);
            }
        }); 
    }
    public void showData(){
        ArrayList<StudentasDuom>studentai=studentai();
        DefaultTableModel model = (DefaultTableModel) StudentuSarasas.getModel();
        Object[]row=new Object[5];
        for(int i=0;i<studentai.size();i++){
            row[0]=studentai.get(i).Nr;
            row[1]=studentai.get(i).vardas;
            row[2]=studentai.get(i).pavarde;
            row[3]=studentai.get(i).dalykai_vidurkiai;
            //System.out.println(studentai.get(i).Nr+studentai.get(i).vardas+studentai.get(i).pavarde+studentai.get(i).dalykai_vidurkiai); 
            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DalykaiIrVidurkiaiUpdate;
    private javax.swing.JButton IstrintiDb;
    private javax.swing.JButton NaujasStudentas;
    private javax.swing.JTextField NrSalinti;
    private javax.swing.JTextField PavardeUpdate;
    private javax.swing.JTextField StDalVid;
    private javax.swing.JTextField StNr;
    private javax.swing.JTextField StPavard;
    private javax.swing.JTextField StVard;
    private javax.swing.JTable StudentuSarasas;
    private javax.swing.JButton UpdateStudentas;
    private javax.swing.JTextField VardasUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
